version: 2.1

orbs:
  slack: circleci/slack@4.3.0

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  deploy:
    docker:
      - image: circleci/node:12.18.0
    resource_class: medium
    steps:
      - trigger_slack_notification
      - checkout
      - run:
          name: Install packages
          command: npm install
      - notify_slack_error
      - notify_slack_pass
